kind: Deployment
apiVersion: apps/v1
metadata:
  name: symfony-demo
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: symfony-demo
  template:
    metadata:
       labels:
          app: symfony-demo
    spec:
      containers:
        - name: symfony-demo
          image: bashofmann/symfony-demo:3.0.0
          livenessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 1
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: symfony-demo
spec:
  type: LoadBalancer
  ports:
  -
    name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: symfony-demo
